"""
Django settings for vinylvibes project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from cryptography.fernet import Fernet, base64


# key = Fernet.generate_key()
# url_safe_key = base64.urlsafe_b64decode(key)
# # print(f'Fernet Key: {url_safe_key.decode()}')
# # # print(key)

# # hola = key.decode()
# # # print(hola)

# SECRET_KEY = url_safe_key
# # print(SECRET_KEY)


LLAVECITA = Fernet.generate_key()


# print(len(SECRET_KEY))



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(*@%5-5+@@14+oz8@benaz-2rmd0))(56uhtoo-)z*^f%69fp('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['Vinylvibes.us-east-2.elasticbeanstalk.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'vinylvibes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vinylvibes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#MYSQL RDS BASE DE DATOS CONFIGURACION/PARAMETROS
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vinylvibesdb',  # Sin llaves angulares
        'USER': 'admin',          # Usuario real de tu base de datos
        'PASSWORD': 'Vynil1234.', # Contraseña de tu base de datos
        'HOST': 'vinylvibes-db.ctsq6sykel8f.us-east-2.rds.amazonaws.com',  # Endpoint de tu servidor MySQL
        'PORT': '3306',           # Puerto predeterminado de MySQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


WEBPAY_API_KEY = "pccyPGcd9uJvI8cXo4F7G/Rn18Ae9D7PvJYJ5C4XX"  # API Key de prueba
WEBPAY_COMMERCE_CODE = "597055555532"  # Código de comercio de prueba
WEBPAY_ENVIRONMENT = "TEST"  # Modo de prueba
WEBPAY_RETURN_URL = "http://127.0.0.1:8000/resultado_pago/"  # URL de retorno después del pago


#LOGS PARA VER LA CONEXION A MYSQL
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    },
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
