# Generated by Django 5.1.1 on 2024-12-04 22:17

import main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='artista',
            field=main.fields.EncryptedCharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=main.fields.EncryptedCharField(max_length=200),
        ),
    ]
